workspace(name = "bzl4")

load(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
)

http_archive(
    name = "platforms",
    urls = [
        "https://github.com/bazelbuild/platforms/archive/e658a6af526089406d0057160542597501ba65d7.tar.gz"
    ],
    sha256 = "056bf8eeb3c49cf215007586943215a5bf3e41205fab99a79a01b0978d4857d0",
    strip_prefix = "platforms-e658a6af526089406d0057160542597501ba65d7",
)

http_archive(
    name = "rules_cc",
    urls = ["https://github.com/bazelbuild/rules_cc/releases/download/0.0.1/rules_cc-0.0.1.tar.gz"],
    sha256 = "4dccbfd22c0def164c8f47458bd50e0c7148f3d92002cdb459c2a96a68498241",
)

http_archive(
    name = "io_tweag_rules_nixpkgs",
    sha256 = "7efb0f82cda5cdaa8e96b687734c5704b91353561d7889e5d84a13b6d30f4cb8",
    strip_prefix = "rules_nixpkgs-05a445575de51872f528c537cc7ff3ab11114f21",
    urls = ["https://github.com/tweag/rules_nixpkgs/archive/05a445575de51872f528c537cc7ff3ab11114f21.tar.gz"],
)

load("@io_tweag_rules_nixpkgs//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")
rules_nixpkgs_dependencies()

load("//third_party/nix:defs.bzl", "NIX_REPOSITORIES", "nix_repositories")
nix_repositories()

load("//third_party/cpp_toolchains:defs.bzl", "cpp_toolchains")
cpp_toolchains()

load("//third_party:dependencies.bzl", "third_party_deps")
third_party_deps()
