workspace(name = "example_project_bzl_4")

load(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
)

http_archive(
    name = "platforms",
    urls = [
        "https://github.com/bazelbuild/platforms/archive/e658a6af526089406d0057160542597501ba65d7.tar.gz"
    ],
    sha256 = "056bf8eeb3c49cf215007586943215a5bf3e41205fab99a79a01b0978d4857d0",
    strip_prefix = "platforms-e658a6af526089406d0057160542597501ba65d7",
)

http_archive(
    name = "rules_cc",
    urls = ["https://github.com/bazelbuild/rules_cc/releases/download/0.0.1/rules_cc-0.0.1.tar.gz"],
    sha256 = "4dccbfd22c0def164c8f47458bd50e0c7148f3d92002cdb459c2a96a68498241",
)

local_repository(
    name = "distruptor_nix",
    path = "../nix",
)

load("@distruptor_nix//bzl:deps.bzl", "distruptor_deps")
distruptor_deps()

load("@distruptor_nix//bzl:deps_init.bzl", "deps_init")
deps_init()

load("@distruptor_nix//bzl:defs.bzl", "nix_repositories_init")
nix_repositories_init()

load("@distruptor_nix//bzl:pkgs.bzl", "nix_packages_init")
nix_packages_init()

load("//third_party/cpp_toolchains:defs.bzl", "cpp_toolchains")
cpp_toolchains()

load("//third_party:dependencies.bzl", "third_party_deps")
third_party_deps()
