name: "Project: bzl4"
on:
  pull_request:
  push:
    branches:
      - "master"
jobs:
  full-build:
    name: build bzl4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses:
          actions/checkout@v2.4.0
          # Flakes do not like shallow clones
        with:
          fetch-depth: 0
      - name: Install nix-shell
        run: ./nix-shell.sh
      - name: Build all
        run: ./nix-shell.sh -- --run 'cd projects/bzl4; bazel build //...'
