name: "Example Project with Bazel 4"
on:
  pull_request:
  push:
    branches:
      - "master"
jobs:
  full-build:
    name: build example_project_bzl_4
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-18.04, macos-latest, macos-10.15 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses:
          actions/checkout@v2.4.0
          # Flakes do not like shallow clones
        with:
          fetch-depth: 0
        # Mandatory to install 'coreutils' on MacOS
      - name: Install dependencies on macOS
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install coreutils
      - name: Build all
        run: ./nix-shell.sh -- --run 'cd example_project_bzl_4; bazel build //...'
