name: "Nix Shell Integrity Check"
on:
  push:
jobs:
  nix-shell-check:
    name: verify nix shell installation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses:
          actions/checkout@v2.4.0
          # Flakes do not like shallow clones
        with:
          fetch-depth: 0
      - name: Install nix-shell
        run: |
          ./nix-shell.sh