name: "ci-checks"
on:
  push:
jobs:
  nix-shell-check:
    name: verify nix shell installation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
       # Flakes do not like shallow clones
      with:
        fetch-depth: 0
    - run: ./nix-shell.sh
